import type { Store } from './types';

export const STORES: Store[] = [
  {
    id: 1,
    name: 'Boutique Rosa',
    ownerName: 'María García',
    whatsapp: '573001234567',
    phone: '+57 300 123 4567',
    address: 'Cra 7 #45-21, Chapinero, Bogotá',
    schedule: 'Lun–Sáb: 9am – 7pm',
    category: 'Moda & Accesorios',
    bio: 'Ropa colombiana hecha a mano con materiales locales.',
    avatarUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
    color: '#ff6b9d',
    accent: '#ff2d78',
    position: [-6, 0, -6],
    rating: 4.8,
    reviews: 214,
    products: [
      {
        id: 101,
        name: 'Camiseta Floral',
        price: 35000,
        stock: 12,
        emoji: '',
        tag: 'Más vendido',
        tagColor: '#e94560',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: '100% algodón colombiano. Tallas XS–XL.',
        colors: ['#f9a8d4', '#86efac', '#93c5fd'],
      },
      {
        id: 102,
        name: 'Vestido Verano',
        price: 85000,
        stock: 5,
        emoji: 'vestido',
        tag: 'Nuevo',
        tagColor: '#6366f1',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: 'Lino natural, fluido y fresco.',
        colors: ['#fde68a', '#fbcfe8', '#a5f3fc'],
      },
    ],
  },
  {
    id: 2,
    name: 'Tech Store',
    ownerName: 'Carlos Ruiz',
    whatsapp: '573009876543',
    phone: '+57 300 987 6543',
    address: 'Av. El Dorado #68-50, Bogotá',
    schedule: 'Lun–Dom: 8am – 9pm',
    category: 'Tecnología',
    bio: 'Accesorios tech de calidad al mejor precio.',
    avatarUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
    color: '#4ecdc4',
    accent: '#00b4aa',
    position: [6, 0, -6],
    rating: 4.6,
    reviews: 98,
    products: [
      {
        id: 201,
        name: 'Audífonos BT',
        price: 120000,
        stock: 7,
        emoji: 'algo',
        tag: 'Top ventas',
        tagColor: '#4ecdc4',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: '40h de batería, cancelación de ruido.',
      },
      {
        id: 202,
        name: 'Power Bank 20k',
        price: 65000,
        stock: 15,
        emoji: '🔋',
        tag: 'Oferta',
        tagColor: '#10b981',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: 'Carga 3 dispositivos simultáneamente.',
      },
    ],
  },
  {
    id: 3,
    name: 'Dulce Repostería',
    ownerName: 'Ana López',
    whatsapp: '573005555555',
    phone: '+57 300 555 5555',
    address: 'Cll 85 #15-32, Usaquén, Bogotá',
    schedule: 'Mar–Dom: 10am – 6pm',
    category: 'Repostería',
    bio: 'Tortas y dulces artesanales hechos con amor.',
    avatarUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
    color: '#ffd93d',
    accent: '#f0b800',
    position: [-6, 0, 6],
    rating: 4.9,
    reviews: 341,
    products: [
      {
        id: 301,
        name: 'Torta Chocolate',
        price: 45000,
        stock: 3,
        emoji: '',
        tag: 'Pedido previo',
        tagColor: '#f59e0b',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: 'Para 12 personas. Relleno de ganache.',
      },
    ],
  },
  {
    id: 4,
    name: 'Eco Tienda',
    ownerName: 'Pedro Mora',
    whatsapp: '573007777777',
    phone: '+57 300 777 7777',
    address: 'Cra 13 #93-40, Bogotá',
    schedule: 'Lun–Sáb: 9am – 5pm',
    category: 'Productos Eco',
    bio: 'Productos sostenibles y libres de plástico.',
    avatarUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
    color: '#6bcb77',
    accent: '#3da849',
    position: [6, 0, 6],
    rating: 4.7,
    reviews: 127,
    products: [
      {
        id: 401,
        name: 'Kit Bambú',
        price: 35000,
        stock: 20,
        emoji: '🎋',
        tag: 'Artesanal',
        tagColor: '#6bcb77',
        imageUrl: 'https://www.udistrital.edu.co/nuestra-universidad/quienes-somos/simbolos',
        description: 'Cepillo de dientes + cepillo facial de bambú.',
      },
    ],
  },
];