/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuscarProducto` | `/BuscarProducto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historialComprador` | `/historialComprador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hubcomprador` | `/hubcomprador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/BuscarProducto` | `/BuscarProducto`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historialComprador` | `/historialComprador`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hubcomprador` | `/hubcomprador`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/BuscarProducto${`?${string}` | `#${string}` | ''}` | `/BuscarProducto${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historialComprador${`?${string}` | `#${string}` | ''}` | `/historialComprador${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hubcomprador${`?${string}` | `#${string}` | ''}` | `/hubcomprador${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/test${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuscarProducto` | `/BuscarProducto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historialComprador` | `/historialComprador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hubcomprador` | `/hubcomprador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownInputParams; };
    }
  }
}
